import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/layout'
import Breathe from '@/components/animation/breath'
import { useSession } from '@supabase/auth-helpers-react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const session = useSession()
  const navList = [
    { name: "About", href: "/about" },
  ]
  if (!session) {
    navList.push({ name: "Login", href: "/login" })
  } else {
    navList.push({ name: "Practice", href: "/practice" })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout navList={navList}>
          <Breathe/>
        </Layout>
      </main>
    </>
  )
}
